language: c
compiler:
  - clang-3.8
  - gcc
sudo: false
before_install:
  - pip install cpp-coveralls --user
  - export LD_LIBRARY_PATH=$PWD/build/dist/lib:$LD_LIBRARY_PATH
env:
#  - USE_CONTEXT=ON
  - USE_CONTEXT=OFF
#  - USE_CONTEXT=OFF USE_EMBEDTLS=ON
matrix:
  exclude:
    - compiler: gcc
      env: USE_CONTEXT=OFF
    - compiler: gcc
      env: USE_CONTEXT=OFF USE_EMBEDTLS=ON
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - llvm-toolchain-precise-3.8
    packages:
    - libssl-dev
    - cmake
    - cmake-data
    - clang-3.8
    - libclang1-3.8
    - libllvm3.8
    - libstdc++6
    - libstdc++-4.9-dev
    - libgcc-4.9-dev
    - libobjc-4.9-dev
    - libclang-common-3.8-dev
script:
  - cmake --version
  - git clone --depth 1 git://github.com/cose-wg/Examples Examples
  - mkdir build
  - cd build && cmake -Duse_context=$USE_CONTEXT -Dcoveralls_send=ON -Duse_embedtls=$USE_EMBEDTLS .. && make all test

after_success:
  - make coveralls


